# Generated by Django 4.1.2 on 2023-03-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_categorie', models.CharField(default='', max_length=50)),
                ('nom_categorie', models.CharField(default='', max_length=30)),
                ('type_doc', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.CharField(default='', max_length=50)),
                ('nom_doc', models.CharField(default='', max_length=30)),
                ('date_creation', models.DateField()),
                ('date_archivage', models.DateField()),
                ('traitement', models.CharField(default='', max_length=30)),
                ('type_doc', models.CharField(default='', max_length=30)),
                ('nom_modifieur', models.CharField(max_length=50)),
                ('date_creation_doc', models.DateField()),
                ('description_doc', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.CharField(default='', max_length=50)),
                ('nom_doc', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Visibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.CharField(default='', max_length=50)),
                ('code_utilisateur', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
